### ISSUE TITLE
failure to resolve large AS-SETs

### ISSUE THREAD

**Issue by wk** [job/irrtree#13]
irrtree v1.3.0 fails to resolve large AS-SET, exiting with IndexError exception after about a minute, example below:

```bash
$ irrtree AS-TINET
Processed: 1 objects (Elapsed Time: 0:01:00)                                                   Traceback (most recent call last):
  File "/usr/local/bin/irrtree", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/irrtree/cli.py", line 240, in main
    prefixes = query(connection, "g" if server.afi == 4 else "6", item, False, False)
  File "/usr/local/lib/python3.7/dist-packages/irrtree/cli.py", line 75, in query
    elif answer[0] == "F":
IndexError: string index out of range
$
```

**Comment by wk** [comment]
This appears to be caused by the remote irrd timing out while irrtree is processing the initial response from expanding an AS-SET to a large number of constituent members.

By the time subsequent queries are sent, the socket closes and further recursive expansion can't continue.
